-- Migration: Create audit_logs table for tracking admin and security events
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    performed_by TEXT NOT NULL,
    details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS and permissive policies for audit_logs
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for everyone" ON audit_logs FOR SELECT USING (true);
CREATE POLICY "Enable insert for everyone" ON audit_logs FOR INSERT WITH CHECK (true);

-- Index for fast audit query sorting
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at DESC);
