-- 1. Enable UUID Extension (in case it is used)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Drop existing tables if they exist to start fresh (reorder to avoid foreign key issues)
DROP TABLE IF EXISTS receipts;
DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS candidates;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS election_settings;

-- 3. Create 'students' table
CREATE TABLE students (
    id TEXT PRIMARY KEY, -- LRN (12 digits stored as text)
    name TEXT NOT NULL,
    password TEXT NOT NULL,
    grade TEXT NOT NULL,
    section TEXT,
    age INTEGER,
    has_voted BOOLEAN DEFAULT FALSE,
    voted_at TIMESTAMPTZ,
    vote_location TEXT,
    photo_url TEXT,
    mobile_number TEXT,
    otp_code TEXT,
    otp_expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create 'candidates' table
CREATE TABLE candidates (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name TEXT NOT NULL,
    position TEXT NOT NULL,
    image_url TEXT,
    campaign_text TEXT,
    age INTEGER,
    section TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create 'votes' table
CREATE TABLE votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT REFERENCES students(id) ON DELETE CASCADE,
    candidate_id TEXT REFERENCES candidates(id) ON DELETE CASCADE,
    position TEXT NOT NULL,
    voted_at TIMESTAMPTZ DEFAULT NOW(),
    location TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Create 'receipts' table
CREATE TABLE receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT REFERENCES students(id) ON DELETE CASCADE,
    receipt_data TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Create 'election_settings' table
CREATE TABLE election_settings (
    id BIGINT PRIMARY KEY DEFAULT 1,
    end_time TIMESTAMPTZ,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Insert a default row for election settings
INSERT INTO election_settings (id, end_time) 
VALUES (1, NOW() + INTERVAL '7 days')
ON CONFLICT (id) DO NOTHING;

-- 9. Enable RLS (Row Level Security) and create permissive public policies
-- This ensures RLS is active while allowing the client to read and write data safely.

-- Students Policies
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for everyone" ON students FOR SELECT USING (true);
CREATE POLICY "Enable insert for everyone" ON students FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for everyone" ON students FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for everyone" ON students FOR DELETE USING (true);

-- Candidates Policies
ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for everyone" ON candidates FOR SELECT USING (true);
CREATE POLICY "Enable insert for everyone" ON candidates FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for everyone" ON candidates FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for everyone" ON candidates FOR DELETE USING (true);

-- Votes Policies
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for everyone" ON votes FOR SELECT USING (true);
CREATE POLICY "Enable insert for everyone" ON votes FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for everyone" ON votes FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for everyone" ON votes FOR DELETE USING (true);

-- Receipts Policies
ALTER TABLE receipts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for everyone" ON receipts FOR SELECT USING (true);
CREATE POLICY "Enable insert for everyone" ON receipts FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for everyone" ON receipts FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for everyone" ON receipts FOR DELETE USING (true);

-- Election Settings Policies
ALTER TABLE election_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for everyone" ON election_settings FOR SELECT USING (true);
CREATE POLICY "Enable insert for everyone" ON election_settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for everyone" ON election_settings FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for everyone" ON election_settings FOR DELETE USING (true);
